INSERT INTO pais (nome, sigla, versao) VALUES
                                           ('Afeganistão', 'AF', 0),
                                           ('Albânia', 'AL', 0),
                                           ('Alemanha', 'DE', 0),
                                           ('Andorra', 'AD', 0),
                                           ('Angola', 'AO', 0),
                                           ('Antígua e Barbuda', 'AG', 0),
                                           ('Arábia Saudita', 'SA', 0),
                                           ('Argélia', 'DZ', 0),
                                           ('Argentina', 'AR', 0),
                                           ('Armênia', 'AM', 0),
                                           ('Austrália', 'AU', 0),
                                           ('Áustria', 'AT', 0),
                                           ('Azerbaijão', 'AZ', 0),
                                           ('Bahamas', 'BS', 0),
                                           ('Bahrein', 'BH', 0),
                                           ('Bangladesh', 'BD', 0),
                                           ('Barbados', 'BB', 0),
                                           ('Bélgica', 'BE', 0),
                                           ('Belize', 'BZ', 0),
                                           ('Benim', 'BJ', 0),
                                           ('Bolívia', 'BO', 0),
                                           ('Bósnia e Herzegovina', 'BA', 0),
                                           ('Botsuana', 'BW', 0),
                                           ('Brasil', 'BR', 0),
                                           ('Brunei', 'BN', 0),
                                           ('Bulgária', 'BG', 0),
                                           ('Burkina Faso', 'BF', 0),
                                           ('Burundi', 'BI', 0),
                                           ('Butão', 'BT', 0),
                                           ('Cabo Verde', 'CV', 0),
                                           ('Camarões', 'CM', 0),
                                           ('Camboja', 'KH', 0),
                                           ('Canadá', 'CA', 0),
                                           ('Catar', 'QA', 0),
                                           ('Cazaquistão', 'KZ', 0),
                                           ('Chade', 'TD', 0),
                                           ('Chile', 'CL', 0),
                                           ('China', 'CN', 0),
                                           ('Chipre', 'CY', 0),
                                           ('Colômbia', 'CO', 0),
                                           ('Comores', 'KM', 0),
                                           ('Congo-Brazzaville', 'CG', 0),
                                           ('Congo-Kinshasa', 'CD', 0),
                                           ('Coreia do Norte', 'KP', 0),
                                           ('Coreia do Sul', 'KR', 0),
                                           ('Costa do Marfim', 'CI', 0),
                                           ('Costa Rica', 'CR', 0),
                                           ('Croácia', 'HR', 0),
                                           ('Cuba', 'CU', 0),
                                           ('Dinamarca', 'DK', 0),
                                           ('Djibuti', 'DJ', 0),
                                           ('Dominica', 'DM', 0),
                                           ('Egito', 'EG', 0),
                                           ('El Salvador', 'SV', 0),
                                           ('Emirados Árabes Unidos', 'AE', 0),
                                           ('Equador', 'EC', 0),
                                           ('Eritreia', 'ER', 0),
                                           ('Eslováquia', 'SK', 0),
                                           ('Eslovênia', 'SI', 0),
                                           ('Espanha', 'ES', 0),
                                           ('Estados Unidos', 'US', 0),
                                           ('Estônia', 'EE', 0),
                                           ('Etiópia', 'ET', 0),
                                           ('Fiji', 'FJ', 0),
                                           ('Filipinas', 'PH', 0),
                                           ('Finlândia', 'FI', 0),
                                           ('França', 'FR', 0),
                                           ('Gabão', 'GA', 0),
                                           ('Gâmbia', 'GM', 0),
                                           ('Gana', 'GH', 0),
                                           ('Geórgia', 'GE', 0),
                                           ('Granada', 'GD', 0),
                                           ('Grécia', 'GR', 0),
                                           ('Guatemala', 'GT', 0),
                                           ('Guiana', 'GY', 0),
                                           ('Guiné', 'GN', 0),
                                           ('Guiné Equatorial', 'GQ', 0),
                                           ('Guiné-Bissau', 'GW', 0),
                                           ('Haiti', 'HT', 0),
                                           ('Honduras', 'HN', 0),
                                           ('Hungria', 'HU', 0),
                                           ('Iêmen', 'YE', 0),
                                           ('Índia', 'IN', 0),
                                           ('Indonésia', 'ID', 0),
                                           ('Irã', 'IR', 0),
                                           ('Iraque', 'IQ', 0),
                                           ('Irlanda', 'IE', 0),
                                           ('Islândia', 'IS', 0),
                                           ('Israel', 'IL', 0),
                                           ('Itália', 'IT', 0),
                                           ('Jamaica', 'JM', 0),
                                           ('Japão', 'JP', 0),
                                           ('Jordânia', 'JO', 0),
                                           ('Kuwait', 'KW', 0),
                                           ('Laos', 'LA', 0),
                                           ('Lesoto', 'LS', 0),
                                           ('Letônia', 'LV', 0),
                                           ('Líbano', 'LB', 0),
                                           ('Libéria', 'LR', 0),
                                           ('Líbia', 'LY', 0),
                                           ('Liechtenstein', 'LI', 0),
                                           ('Lituânia', 'LT', 0),
                                           ('Luxemburgo', 'LU', 0),
                                           ('Macedônia do Norte', 'MK', 0),
                                           ('Madagascar', 'MG', 0),
                                           ('Malásia', 'MY', 0),
                                           ('Malaui', 'MW', 0),
                                           ('Maldivas', 'MV', 0),
                                           ('Mali', 'ML', 0),
                                           ('Malta', 'MT', 0),
                                           ('Marrocos', 'MA', 0),
                                           ('Maurícia', 'MU', 0),
                                           ('Mauritânia', 'MR', 0),
                                           ('México', 'MX', 0),
                                           ('Mianmar', 'MM', 0),
                                           ('Micronésia', 'FM', 0),
                                           ('Moçambique', 'MZ', 0),
                                           ('Moldávia', 'MD', 0),
                                           ('Mônaco', 'MC', 0),
                                           ('Mongólia', 'MN', 0),
                                           ('Montenegro', 'ME', 0),
                                           ('Namíbia', 'NA', 0),
                                           ('Nauru', 'NR', 0),
                                           ('Nepal', 'NP', 0),
                                           ('Nicarágua', 'NI', 0),
                                           ('Níger', 'NE', 0),
                                           ('Nigéria', 'NG', 0),
                                           ('Noruega', 'NO', 0),
                                           ('Nova Zelândia', 'NZ', 0),
                                           ('Omã', 'OM', 0),
                                           ('Países Baixos', 'NL', 0),
                                           ('Palau', 'PW', 0),
                                           ('Panamá', 'PA', 0),
                                           ('Papua-Nova Guiné', 'PG', 0),
                                           ('Paquistão', 'PK', 0),
                                           ('Paraguai', 'PY', 0),
                                           ('Peru', 'PE', 0),
                                           ('Polônia', 'PL', 0),
                                           ('Portugal', 'PT', 0),
                                           ('Quênia', 'KE', 0),
                                           ('Quirguistão', 'KG', 0),
                                           ('Reino Unido', 'GB', 0),
                                           ('República Centro-Africana', 'CF', 0),
                                           ('República Dominicana', 'DO', 0),
                                           ('República Tcheca', 'CZ', 0),
                                           ('Romênia', 'RO', 0),
                                           ('Ruanda', 'RW', 0),
                                           ('Rússia', 'RU', 0),
                                           ('Samoa', 'WS', 0),
                                           ('San Marino', 'SM', 0),
                                           ('Santa Lúcia', 'LC', 0),
                                           ('São Cristóvão e Névis', 'KN', 0),
                                           ('São Tomé e Príncipe', 'ST', 0),
                                           ('São Vicente e Granadinas', 'VC', 0),
                                           ('Senegal', 'SN', 0),
                                           ('Serra Leoa', 'SL', 0),
                                           ('Sérvia', 'RS', 0),
                                           ('Seychelles', 'SC', 0),
                                           ('Singapura', 'SG', 0),
                                           ('Síria', 'SY', 0),
                                           ('Somália', 'SO', 0),
                                           ('Sri Lanka', 'LK', 0),
                                           ('Suazilândia', 'SZ', 0),
                                           ('Sudão', 'SD', 0),
                                           ('Sudão do Sul', 'SS', 0),
                                           ('Suécia', 'SE', 0),
                                           ('Suíça', 'CH', 0),
                                           ('Suriname', 'SR', 0),
                                           ('Tailândia', 'TH', 0),
                                           ('Taiwan', 'TW', 0),
                                           ('Tajiquistão', 'TJ', 0),
                                           ('Tanzânia', 'TZ', 0),
                                           ('Timor-Leste', 'TL', 0),
                                           ('Togo', 'TG', 0),
                                           ('Tonga', 'TO', 0),
                                           ('Trinidad e Tobago', 'TT', 0),
                                           ('Tunísia', 'TN', 0),
                                           ('Turcomenistão', 'TM', 0),
                                           ('Turquia', 'TR', 0),
                                           ('Tuvalu', 'TV', 0),
                                           ('Ucrânia', 'UA', 0),
                                           ('Uganda', 'UG', 0),
                                           ('Uruguai', 'UY', 0),
                                           ('Uzbequistão', 'UZ', 0),
                                           ('Vanuatu', 'VU', 0),
                                           ('Vaticano', 'VA', 0),
                                           ('Venezuela', 'VE', 0),
                                           ('Vietnã', 'VN', 0),
                                           ('Zâmbia', 'ZM', 0),
                                           ('Zimbábue', 'ZW', 0);


INSERT INTO estado (pais, nome, sigla, codibge, versao) VALUES
                                                            ((SELECT id FROM pais WHERE sigla = 'BR'), 'Acre', 'AC', '12', 0),
                                                            ((SELECT id FROM pais WHERE sigla = 'BR'), 'Alagoas', 'AL', '27', 0),
                                                            ((SELECT id FROM pais WHERE sigla = 'BR'), 'Amapá', 'AP', '16', 0),
                                                            ((SELECT id FROM pais WHERE sigla = 'BR'), 'Amazonas', 'AM', '13', 0),
                                                            ((SELECT id FROM pais WHERE sigla = 'BR'), 'Bahia', 'BA', '29', 0),
                                                            ((SELECT id FROM pais WHERE sigla = 'BR'), 'Ceará', 'CE', '23', 0),
                                                            ((SELECT id FROM pais WHERE sigla = 'BR'), 'Distrito Federal', 'DF', '53', 0),
                                                            ((SELECT id FROM pais WHERE sigla = 'BR'), 'Espírito Santo', 'ES', '32', 0),
                                                            ((SELECT id FROM pais WHERE sigla = 'BR'), 'Goiás', 'GO', '52', 0),
                                                            ((SELECT id FROM pais WHERE sigla = 'BR'), 'Maranhão', 'MA', '21', 0),
                                                            ((SELECT id FROM pais WHERE sigla = 'BR'), 'Mato Grosso', 'MT', '51', 0),
                                                            ((SELECT id FROM pais WHERE sigla = 'BR'), 'Mato Grosso do Sul', 'MS', '50', 0),
                                                            ((SELECT id FROM pais WHERE sigla = 'BR'), 'Minas Gerais', 'MG', '31', 0),
                                                            ((SELECT id FROM pais WHERE sigla = 'BR'), 'Pará', 'PA', '15', 0),
                                                            ((SELECT id FROM pais WHERE sigla = 'BR'), 'Paraíba', 'PB', '25', 0),
                                                            ((SELECT id FROM pais WHERE sigla = 'BR'), 'Paraná', 'PR', '41', 0),
                                                            ((SELECT id FROM pais WHERE sigla = 'BR'), 'Pernambuco', 'PE', '26', 0),
                                                            ((SELECT id FROM pais WHERE sigla = 'BR'), 'Piauí', 'PI', '22', 0),
                                                            ((SELECT id FROM pais WHERE sigla = 'BR'), 'Rio de Janeiro', 'RJ', '33', 0),
                                                            ((SELECT id FROM pais WHERE sigla = 'BR'), 'Rio Grande do Norte', 'RN', '24', 0),
                                                            ((SELECT id FROM pais WHERE sigla = 'BR'), 'Rio Grande do Sul', 'RS', '43', 0),
                                                            ((SELECT id FROM pais WHERE sigla = 'BR'), 'Rondônia', 'RO', '11', 0),
                                                            ((SELECT id FROM pais WHERE sigla = 'BR'), 'Roraima', 'RR', '14', 0),
                                                            ((SELECT id FROM pais WHERE sigla = 'BR'), 'Santa Catarina', 'SC', '42', 0),
                                                            ((SELECT id FROM pais WHERE sigla = 'BR'), 'São Paulo', 'SP', '35', 0),
                                                            ((SELECT id FROM pais WHERE sigla = 'BR'), 'Sergipe', 'SE', '28', 0),
                                                            ((SELECT id FROM pais WHERE sigla = 'BR'), 'Tocantins', 'TO', '17', 0);